### ISSUE TITLE
shcov doesn't work while sudo

### ISSUE THREAD

**Issue by YvesZHI** [SimonKagstrom/shcov#4]
`shcov` can't work as expected while sudo.<br>

For example, a script named `1.sh` as below:
```
#!/bin/sh
echo NOTHING
``` 

`shcov 1.sh` gives me<br>

> NOTHING

`sudo shcov 1.sh` gives me<br>

> NOTHING
> \+ echo NOTHING

The reason is [here](https://stackoverflow.com/questions/48075303/python-subprocess-gives-me-different-results-while-using-sudo). 

In a word, the recent bash doesn't allow changing `PS4` while sudo.

**Comment by SimonKagstrom** [comment]
Thanks for the report!

I should say that I don't develop shcov anymore: it has been replaced by [kcov](https://github.com/SimonKagstrom/kcov) (which has a lot more features). In kcov you can run with either PS4 or bash DEBUG traps. At least on my system, kcov works with sudo using ```--bash-method=DEBUG```

**Comment by YvesZHI** [comment]
@SimonKagstrom Great, then I ll use kcov now. You can close this issue.
